import { Inter } from 'next/font/google'
import './globals.css'
import { AuthUserProvider } from '@/context/AuthUserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alpha Bi Technical Intern Test',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (<AuthUserProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </AuthUserProvider>
  )
}
